server:
  port: 8081

spring:
  rsocket:
    server:
      port: 7001

database:
  host: localhost
  port: 5432
  name: rsocket_customer
  username: ${DATABASE_USERNAME}
  password: ${DATABASE_PASSWORD}
